import 'package:flutter/material.dart';

import '../modelos/categoria_gasto.dart';
import '../modelos/movimiento.dart';
import '../tema/colores_app.dart';

const categoriasGasto = [
  CategoriaGasto(
    nombre: 'Alimentacion',
    icono: Icons.restaurant_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Supermercado',
    icono: Icons.local_grocery_store_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Despensa',
    icono: Icons.storefront_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Verduleria',
    icono: Icons.eco_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Carniceria',
    icono: Icons.set_meal_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Panaderia',
    icono: Icons.bakery_dining_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Restaurantes',
    icono: Icons.dinner_dining_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Delivery',
    icono: Icons.delivery_dining_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cafe',
    icono: Icons.local_cafe_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Snacks',
    icono: Icons.cookie_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Agua y bebidas',
    icono: Icons.local_drink_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mercado familiar',
    icono: Icons.shopping_cart_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Hogar',
    icono: Icons.home_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Alquiler',
    icono: Icons.apartment_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Hipoteca',
    icono: Icons.house_siding_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Expensas',
    icono: Icons.domain_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Muebles',
    icono: Icons.chair_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Decoracion',
    icono: Icons.light_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Limpieza',
    icono: Icons.cleaning_services_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Lavanderia',
    icono: Icons.local_laundry_service_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Reparaciones',
    icono: Icons.handyman_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Jardin',
    icono: Icons.grass_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Electricidad',
    icono: Icons.bolt_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Agua',
    icono: Icons.water_drop_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Gas',
    icono: Icons.local_fire_department_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Internet',
    icono: Icons.wifi_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Telefono',
    icono: Icons.phone_android_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cable TV',
    icono: Icons.tv_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Transporte',
    icono: Icons.directions_car_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Bus',
    icono: Icons.directions_bus_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Taxi',
    icono: Icons.local_taxi_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Uber/Bolt',
    icono: Icons.hail_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Combustible',
    icono: Icons.local_gas_station_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Estacionamiento',
    icono: Icons.local_parking_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Peaje',
    icono: Icons.toll_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mantenimiento auto',
    icono: Icons.car_repair_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Seguro vehiculo',
    icono: Icons.verified_user_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Moto',
    icono: Icons.two_wheeler_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Bicicleta',
    icono: Icons.pedal_bike_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Salud',
    icono: Icons.local_hospital_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Farmacia',
    icono: Icons.medication_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Consultas medicas',
    icono: Icons.medical_services_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Dentista',
    icono: Icons.health_and_safety_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Analisis',
    icono: Icons.science_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Terapia',
    icono: Icons.psychology_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Gimnasio',
    icono: Icons.fitness_center_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Deportes',
    icono: Icons.sports_soccer_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Belleza',
    icono: Icons.spa_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Peluqueria',
    icono: Icons.content_cut_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cuidado personal',
    icono: Icons.face_retouching_natural_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Educacion',
    icono: Icons.school_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cursos',
    icono: Icons.menu_book_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Libros',
    icono: Icons.auto_stories_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Universidad',
    icono: Icons.account_balance_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Utiles',
    icono: Icons.edit_note_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Software educativo',
    icono: Icons.computer_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Ropa',
    icono: Icons.checkroom_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Calzado',
    icono: Icons.directions_walk_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Accesorios',
    icono: Icons.watch_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Uniformes',
    icono: Icons.badge_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Niños',
    icono: Icons.child_care_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Juguetes',
    icono: Icons.toys_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mascotas',
    icono: Icons.pets_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Veterinaria',
    icono: Icons.local_hospital_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Alimento mascota',
    icono: Icons.pets,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Paseador/guarderia',
    icono: Icons.cruelty_free_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Diversion',
    icono: Icons.confirmation_number_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cine',
    icono: Icons.movie_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Conciertos',
    icono: Icons.music_note_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Juegos',
    icono: Icons.sports_esports_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Streaming',
    icono: Icons.play_circle_outline,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Musica',
    icono: Icons.library_music_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Hobbies',
    icono: Icons.palette_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Salidas',
    icono: Icons.nightlife_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Viajes',
    icono: Icons.flight_takeoff_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Hotel',
    icono: Icons.hotel_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Pasajes',
    icono: Icons.airplane_ticket_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Turismo',
    icono: Icons.map_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Equipaje',
    icono: Icons.luggage_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Regalos',
    icono: Icons.card_giftcard_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cumpleaños',
    icono: Icons.cake_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Donaciones',
    icono: Icons.volunteer_activism_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Iglesia/comunidad',
    icono: Icons.groups_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Ahorro',
    icono: Icons.savings_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Inversiones',
    icono: Icons.trending_up_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Emergencias',
    icono: Icons.emergency_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Deudas',
    icono: Icons.account_balance_wallet_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Prestamos',
    icono: Icons.payments_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Tarjeta credito',
    icono: Icons.credit_card_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Banco',
    icono: Icons.account_balance_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Impuestos',
    icono: Icons.request_quote_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Multas',
    icono: Icons.gavel_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Trabajo',
    icono: Icons.work_outline,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Herramientas',
    icono: Icons.build_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Papeleria',
    icono: Icons.description_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Coworking',
    icono: Icons.business_center_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Marketing',
    icono: Icons.campaign_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Tecnologia',
    icono: Icons.devices_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Celular',
    icono: Icons.smartphone_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Computadora',
    icono: Icons.laptop_mac_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Apps',
    icono: Icons.apps_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Suscripciones',
    icono: Icons.subscriptions_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Nube/hosting',
    icono: Icons.cloud_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Seguros',
    icono: Icons.shield_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Seguro medico',
    icono: Icons.health_and_safety_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Seguro hogar',
    icono: Icons.home_work_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Guarderia',
    icono: Icons.escalator_warning_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Niñera',
    icono: Icons.family_restroom_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mesada',
    icono: Icons.wallet_giftcard_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Comedor escolar',
    icono: Icons.lunch_dining_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Excursiones',
    icono: Icons.tour_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Fotocopias',
    icono: Icons.copy_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Matricula',
    icono: Icons.assignment_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cuota colegio',
    icono: Icons.school_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cuota club',
    icono: Icons.sports_tennis_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Piscina',
    icono: Icons.pool_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Clases particulares',
    icono: Icons.record_voice_over_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Idiomas',
    icono: Icons.translate_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Musica/clases',
    icono: Icons.piano_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Arte/manualidades',
    icono: Icons.brush_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Costura',
    icono: Icons.cut_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Maquillaje',
    icono: Icons.color_lens_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Perfumes',
    icono: Icons.air_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Joyeria',
    icono: Icons.diamond_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Optica',
    icono: Icons.visibility_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Lentes',
    icono: Icons.remove_red_eye_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Vacunas',
    icono: Icons.vaccines_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Hospitalizacion',
    icono: Icons.personal_injury_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Embarazo/bebe',
    icono: Icons.pregnant_woman_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Adultos mayores',
    icono: Icons.elderly_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Tramites',
    icono: Icons.fact_check_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Documentos',
    icono: Icons.badge_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Correo/envios',
    icono: Icons.local_shipping_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mudanza',
    icono: Icons.move_down_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Deposito/almacen',
    icono: Icons.warehouse_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Seguridad',
    icono: Icons.security_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cerrajeria',
    icono: Icons.key_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Plomeria',
    icono: Icons.plumbing_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Pintura',
    icono: Icons.format_paint_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Construccion',
    icono: Icons.construction_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Electrodomesticos',
    icono: Icons.kitchen_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Heladera',
    icono: Icons.kitchen_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Aire acondicionado',
    icono: Icons.ac_unit_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Energia solar',
    icono: Icons.solar_power_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Eventos',
    icono: Icons.event_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Boda',
    icono: Icons.favorite_outline,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Fiestas',
    icono: Icons.celebration_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Fotografia',
    icono: Icons.photo_camera_outlined,
    color: ColoresApp.lila,
    colorSuave: ColoresApp.lilaSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mascota baño',
    icono: Icons.shower_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Mascota juguetes',
    icono: Icons.toys_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cripto',
    icono: Icons.currency_bitcoin_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cambio moneda',
    icono: Icons.currency_exchange_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Cajero automatico',
    icono: Icons.atm_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Comisiones bancarias',
    icono: Icons.price_change_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Transferencias',
    icono: Icons.swap_horiz_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Otro gasto',
    icono: Icons.more_horiz,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
];

const categoriasIngreso = [
  CategoriaGasto(
    nombre: 'Salario',
    icono: Icons.payments_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Adelanto',
    icono: Icons.schedule_send_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Aguinaldo',
    icono: Icons.card_giftcard_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Bonificacion',
    icono: Icons.stars_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Horas extra',
    icono: Icons.more_time_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Freelance',
    icono: Icons.work_outline,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Ventas',
    icono: Icons.storefront_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Servicios cobrados',
    icono: Icons.handshake_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Comisiones',
    icono: Icons.percent_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Propinas',
    icono: Icons.volunteer_activism_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Reembolso',
    icono: Icons.replay_outlined,
    color: ColoresApp.celeste,
    colorSuave: ColoresApp.celesteSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Prestamo recibido',
    icono: Icons.account_balance_wallet_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Regalo recibido',
    icono: Icons.redeem_outlined,
    color: ColoresApp.durazno,
    colorSuave: ColoresApp.duraznoSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Alquiler cobrado',
    icono: Icons.apartment_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Dividendos',
    icono: Icons.trending_up_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Intereses',
    icono: Icons.savings_outlined,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Premio',
    icono: Icons.emoji_events_outlined,
    color: ColoresApp.amarillo,
    colorSuave: ColoresApp.amarilloSuave,
    presupuesto: 0,
  ),
  CategoriaGasto(
    nombre: 'Otro ingreso',
    icono: Icons.add_circle_outline,
    color: ColoresApp.verde,
    colorSuave: ColoresApp.verdeSuave,
    presupuesto: 0,
  ),
];

List<Movimiento> movimientosIniciales() {
  return [];
}
